STORAGE_ACCOUNT_NAME = 'logodetectionstorage'
STORAGE_ACCOUNT_KEY = 'SSE8ZyN+VmpxvURBixX4d8w5Xmuc+HjTYqni0vQFWjM1t56I8pgElBzj6eyrcJ0+uD2997tpNgTxeGPf1k0R3Q=='
INPUT_CONTAINER_NAME = 'input'
OUTPUT_CONTAINER_NAME = 'output'

TRAINING_DIRECTORY_NAME = 'training'
OPERATIONAL_DIRECTORY_NAME = 'operational'