# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('max_images', models.PositiveIntegerField(default=10)),
                ('date', models.DateTimeField(verbose_name='Publish Date')),
            ],
        ),
    ]
