# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrequest',
            name='hashtag',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandrequest',
            name='date',
            field=models.DateTimeField(verbose_name='Search Date'),
        ),
    ]
