# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20171008_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_directory_name', models.CharField(max_length=50)),
                ('no_logo_directory_name', models.CharField(max_length=50)),
            ],
        ),
    ]
